config:
  credentials: []
  project_repos:
    github.com/ARGOeu/eosc-recommender-metrics:
      branch: devel
      repo: https://github.com/ARGOeu/eosc-recommender-metrics/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-crimson-toad.sh
        container: qc.acc_shaggy-linen-paradise
  QC.Doc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-black-clam.sh
        container: qc.doc_crappy-chocolate-blue
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-sepia-heron.sh
        container: qc.doc_slimy-bronze-mouse
      github.com/ARGOeu/eosc-recommender-metrics markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-periwinkle-neanderthal.sh
        container: qc.doc_cozy-heliotrope-eagle
  QC.Lic:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-mustard-beaver.sh
        container: qc.lic_wimpy-taupe-ray
  QC.Met:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-pumpkin-gorilla.sh
        container: qc.met_sleazy-firebrick-spaniel
  QC.Sec:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-xanthic-dalmatian.sh
        container: qc.sec_sickly-bistre-squid
  QC.Sty:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-grey-beaver.sh
        container: qc.sty_skinny-thistle-dachshund
      github.com/ARGOeu/eosc-recommender-metrics jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-khaki-kiwi.sh
        container: qc.sty_pretty-buff-akita
  QC.Ver:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-cerulean-vole.sh
        container: qc.ver_hilly-ultramarine-falcon
timeout: 5400
