config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/onedataSim:
      branch: dev
      repo: https://github.com/EOSC-synergy/onedataSim/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/onedataSim git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-puce-worm.sh
        container: qc.acc_randy-violet-wolverine
  QC.Doc:
    repos:
      github.com/EOSC-synergy/onedataSim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-persimmon-audemer.sh
        container: qc.doc_gimpy-wheat-spider
      github.com/EOSC-synergy/onedataSim git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-ruby-warthog.sh
        container: qc.doc_randy-firebrick-rhinoceros
      github.com/EOSC-synergy/onedataSim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-ecru-binturong.sh
        container: qc.doc_breezy-teal-termite
  QC.Lic:
    repos:
      github.com/EOSC-synergy/onedataSim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-crimson-vulture.sh
        container: qc.lic_stinky-alizarin-turtle
  QC.Sec:
    repos:
      github.com/EOSC-synergy/onedataSim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-coral-newfoundland.sh
        container: qc.sec_wiggy-salmon-mule
  QC.Sty:
    repos:
      github.com/EOSC-synergy/onedataSim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-denim-emu.sh
        container: qc.sty_chewy-white-ray
      github.com/EOSC-synergy/onedataSim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-magnolia-balinese.sh
        container: qc.sty_squirrely-russet-nightingale
      github.com/EOSC-synergy/onedataSim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-bronze-capybara.sh
        container: qc.sty_zippy-azure-tiger
      github.com/EOSC-synergy/onedataSim rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-bronze-bison.sh
        container: qc.sty_frumpy-rose-cougar
  QC.Ver:
    repos:
      github.com/EOSC-synergy/onedataSim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-salmon-terrier.sh
        container: qc.ver_sleepy-coral-bloodhound
timeout: 1800
