config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: devel
      repo: https://github.com/grycap/im/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-violet-emu.sh
        container: qc.acc_smelly-wisteria-akbash
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-pumpkin-woodlouse.sh
        container: qc.doc_skimpy-puce-axolotl
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-viridian-olm.sh
        container: qc.doc_blurry-olivine-chipmunk
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-charcoal-cattle.sh
        container: qc.doc_muzzy-charcoal-moorhen
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-lemon-monkey.sh
        container: qc.doc_paltry-carmine-angelfish
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-seashell-zonkey.sh
        container: qc.lic_beady-scarlet-leopard
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.beady-amethyst-emu.sh
        container: qc.met_trippy-rust-frigatebird
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-cardinal-turtle.sh
        container: qc.sec_bumpy-yellow-dane
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-teal-lionfish.sh
        container: qc.sty_squeaky-lime-javanese
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-lime-scorpion.sh
        container: qc.sty_freaky-viridian-sponge
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-champagne-collie.sh
        container: qc.sty_muggy-wheat-llama
      github.com/grycap/im rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-amaranth-woodpecker.sh
        container: qc.sty_surly-orchid-gorilla
      github.com/grycap/im stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-myrtle-coyote.sh
        container: qc.sty_ugly-aqua-coral
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-olive-ostrich.sh
        container: qc.ver_lumpy-grey-whippet
timeout: 1800
