config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/themiszamani/eosc-recommender-metrics:
      branch: QC.Doc02.X-updates
      repo: https://github.com/themiszamani/eosc-recommender-metrics/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/themiszamani/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-heliotrope-wolf.sh
        container: qc.acc_bumpy-lemon-stingray
  QC.Doc:
    repos:
      github.com/themiszamani/eosc-recommender-metrics find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-periwinkle-armadillo.sh
        container: qc.doc_seedy-chestnut-antelope
      github.com/themiszamani/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-brown-pig.sh
        container: qc.doc_blurry-khaki-swan
      github.com/themiszamani/eosc-recommender-metrics markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-brass-lizard.sh
        container: qc.doc_scummy-sepia-crab
  QC.Lic:
    repos:
      github.com/themiszamani/eosc-recommender-metrics licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-scarlet-civet.sh
        container: qc.lic_leaky-vermilion-blue
  QC.Met:
    repos:
      github.com/themiszamani/eosc-recommender-metrics cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-grey-shrew.sh
        container: qc.met_flaky-turquoise-llama
  QC.Sec:
    repos:
      github.com/themiszamani/eosc-recommender-metrics bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-cerise-camel.sh
        container: qc.sec_randy-silver-serval
  QC.Sty:
    repos:
      github.com/themiszamani/eosc-recommender-metrics flake8:
        commands:
        - /usr/bin/env sh .sqa/script.surly-apricot-civet.sh
        container: qc.sty_baggy-beige-discus
      github.com/themiszamani/eosc-recommender-metrics jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-ultramarine-mandrill.sh
        container: qc.sty_bumpy-red-snake
  QC.Ver:
    repos:
      github.com/themiszamani/eosc-recommender-metrics get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-russet-meerkat.sh
        container: qc.ver_slimy-beige-hound
timeout: 5400
