config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cdc.searchkit/src/master:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cdc.searchkit/src/master/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-bistre-bullfrog.sh
        container: qc.acc_frumpy-myrtle-terrier
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-sepia-caterpillar.sh
        container: qc.doc_jumpy-heliotrope-kangaroo
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-emerald-bear.sh
        container: qc.doc_thirsty-ivory-okapi
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-seashell-bombay.sh
        container: qc.doc_leaky-wheat-spitz
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-amethyst-tang.sh
        container: qc.lic_beady-alizarin-dhole
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-khaki-moth.sh
        container: qc.sty_frumpy-alizarin-labradoodle
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-ivory-ant.sh
        container: qc.sty_sleazy-cyan-shrew
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-cerise-dalmatian.sh
        container: qc.sty_cheeky-malachite-tuatara
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-xanthic-greyhound.sh
        container: qc.ver_leaky-amaranth-tarsier
timeout: 5400
