config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cdc.searchkit/src/master:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cdc.searchkit/src/master/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-gold-chin.sh
        container: qc.acc_dorky-firebrick-fossa
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-amethyst-frise.sh
        container: qc.doc_clammy-cyan-wolf
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-mauve-horse.sh
        container: qc.doc_crappy-olivine-butterfly
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-denim-oyster.sh
        container: qc.doc_muzzy-plum-falcon
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-orange-quetzal.sh
        container: qc.lic_wheezy-asparagus-caracal
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-chestnut-peccary.sh
        container: qc.met_homey-lilac-barracuda
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-brown-squirt.sh
        container: qc.sty_queasy-periwinkle-falcon
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-gamboge-urchin.sh
        container: qc.sty_paltry-dandelion-macaque
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-teal-chimpanzee.sh
        container: qc.sty_woolly-grey-vulture
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-cerise-woodpecker.sh
        container: qc.ver_chewy-tomato-hornet
timeout: 5400
