config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: devel
      repo: https://github.com/grycap/im/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-russet-setter.sh
        container: qc.acc_foggy-chestnut-ocelot
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-corn-bombay.sh
        container: qc.doc_fuzzy-linen-uguisu
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-jade-avocet.sh
        container: qc.doc_dorky-sapphire-fish
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-cardinal-seahorse.sh
        container: qc.doc_snazzy-red-tapir
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-bronze-havanese.sh
        container: qc.doc_gummy-cobalt-monkey
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-jade-collie.sh
        container: qc.lic_scanty-maroon-macaw
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.randy-coral-paradise.sh
        container: qc.met_chewy-coral-tetra
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-emerald-woodpecker.sh
        container: qc.sec_snippy-persimmon-beagle
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-corn-maltese.sh
        container: qc.sty_snazzy-taupe-rhinoceros
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-cinnamon-armadillo.sh
        container: qc.sty_scummy-violet-lizard
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-maroon-corgi.sh
        container: qc.sty_slaphappy-azure-walrus
      github.com/grycap/im rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.ready-mustard-numbat.sh
        container: qc.sty_homey-periwinkle-audemer
      github.com/grycap/im stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-ivory-liger.sh
        container: qc.sty_shaky-orange-monster
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-orange-turtle.sh
        container: qc.ver_homely-bronze-fly
timeout: 1800
