config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: 450-improve-SQA-rating
      repo: https://bitbucket.org/cessda/cessda.cvs.two/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-red-greyhound.sh
        container: qc.acc_silly-persimmon-uakari
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-cream-spaniel.sh
        container: qc.doc_blurry-bistre-dollar
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-chocolate-bandicoot.sh
        container: qc.doc_slimy-pink-kingfisher
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-sepia-fly.sh
        container: qc.doc_tasty-eggplant-toucan
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-fuchsia-iguana.sh
        container: qc.lic_beady-ochre-hummingbird
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cvs.two cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-amber-urchin.sh
        container: qc.met_tacky-ruby-mole
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-auburn-saola.sh
        container: qc.sty_sloppy-dandelion-quoll
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-eggplant-lynx.sh
        container: qc.sty_woolly-green-bonobo
      bitbucket.org/cessda/cessda.cvs.two stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-buff-impala.sh
        container: qc.sty_bumpy-cornflower-mongoose
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-bronze-malamute.sh
        container: qc.ver_beady-chartreuse-clam
timeout: 1800
