config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cdc.searchkit/src/master:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cdc.searchkit/src/master/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-thistle-gecko.sh
        container: qc.acc_flaky-persimmon-blue
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-ochre-jackal.sh
        container: qc.doc_woozy-denim-avocet
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-teal-kangaroo.sh
        container: qc.doc_frumpy-green-squirt
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-white-buzzard.sh
        container: qc.doc_cheeky-cinnamon-wolfhound
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-platinum-dachsbracke.sh
        container: qc.lic_stinky-carmine-gibbon
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-linen-barnacle.sh
        container: qc.met_squeaky-ivory-flounder
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-razzmatazz-seahorse.sh
        container: qc.sty_sleazy-lavender-havanese
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-auburn-manatee.sh
        container: qc.sty_skanky-dandelion-penguin
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-aqua-zebu.sh
        container: qc.sty_trippy-aquamarine-quetzal
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-razzmatazz-goat.sh
        container: qc.ver_shaggy-yellow-armadillo
timeout: 5400
