config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: 450-improve-SQA-rating
      repo: https://bitbucket.org/cessda/cessda.cvs.two/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-burgundy-toad.sh
        container: qc.acc_jumpy-turquoise-husky
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-jade-bobcat.sh
        container: qc.doc_ugly-malachite-balinese
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-ochre-crab.sh
        container: qc.doc_stuffy-lilac-hamster
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cardinal-sponge.sh
        container: qc.doc_hilly-fuchsia-tiger
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-carmine-barnacle.sh
        container: qc.lic_woolly-periwinkle-macaw
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cvs.two cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-violet-orangutan.sh
        container: qc.met_scaly-maroon-dormouse
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-sapphire-zebu.sh
        container: qc.sty_skinny-seashell-angelfish
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-carmine-millipede.sh
        container: qc.sty_wimpy-auburn-hornet
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-platinum-dunker.sh
        container: qc.ver_messy-brass-dugong
timeout: 5400
