config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cvs.two/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-fuchsia-hedgehog.sh
        container: qc.acc_greasy-orange-malamute
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-persimmon-dhole.sh
        container: qc.doc_flabby-lime-quokka
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-periwinkle-caterpillar.sh
        container: qc.doc_trippy-dandelion-foxhound
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-cerulean-mouse.sh
        container: qc.doc_hazy-chartreuse-dachsbracke
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-periwinkle-penguin.sh
        container: qc.lic_freaky-gamboge-octopus
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-razzmatazz-mouse.sh
        container: qc.sty_scanty-ruby-bonobo
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-mauve-fousek.sh
        container: qc.sty_snappy-indigo-bison
      bitbucket.org/cessda/cessda.cvs.two stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-pumpkin-quoll.sh
        container: qc.sty_wheezy-orange-wombat
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-sapphire-drever.sh
        container: qc.ver_ready-brown-capuchin
timeout: 5400
