config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: 450-improve-SQA-rating
      repo: https://bitbucket.org/cessda/cessda.cvs.two/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-sepia-hummingbird.sh
        container: qc.acc_clammy-apricot-fox
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-brass-goose.sh
        container: qc.doc_stealthy-scarlet-sheep
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-ultramarine-seal.sh
        container: qc.doc_slimy-yellow-chicken
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-heliotrope-turtle.sh
        container: qc.doc_woolly-harlequin-mongrel
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-corn-stoat.sh
        container: qc.lic_cranky-beige-retriever
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cvs.two cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-amber-fly.sh
        container: qc.met_randy-cerulean-dugong
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-blue-chow.sh
        container: qc.sty_gloppy-goldenrod-sheepdog
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-lime-heron.sh
        container: qc.sty_snazzy-cardinal-lion
      bitbucket.org/cessda/cessda.cvs.two stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-cream-bobcat.sh
        container: qc.sty_clammy-fuchsia-buzzard
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-heliotrope-ostrich.sh
        container: qc.ver_thirsty-olivine-flamingo
timeout: 1800
