config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-messaging:
      branch: devel
      repo: https://github.com/ARGOeu/argo-messaging/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-auburn-lemming.sh
        container: qc.acc_jumpy-russet-quokka
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-messaging find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-blue-quokka.sh
        container: qc.doc_randy-ultramarine-bison
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-chestnut-harrier.sh
        container: qc.doc_randy-corn-coyote
      github.com/ARGOeu/argo-messaging markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-carmine-termite.sh
        container: qc.doc_lousy-tan-collie
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-messaging licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-fuchsia-mastiff.sh
        container: qc.lic_lousy-silver-tiger
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-messaging bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-tan-mau.sh
        container: qc.sec_beady-amethyst-zebu
      github.com/ARGOeu/argo-messaging gosec:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cerulean-guppy.sh
        container: qc.sec_cheeky-grey-hippopotamus
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-messaging flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-amaranth-vole.sh
        container: qc.sty_wiggy-chestnut-falcon
      github.com/ARGOeu/argo-messaging jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-cerise-russel.sh
        container: qc.sty_cozy-alizarin-pinscher
      github.com/ARGOeu/argo-messaging staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-xanthic-bandicoot.sh
        container: qc.sty_woozy-aqua-cassowary
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-messaging get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-seashell-abyssinian.sh
        container: qc.ver_woozy-tangerine-rat
timeout: 5400
