config:
  credentials: []
  project_repos:
    github.com/AI4S2S/lilio:
      branch: main
      repo: https://github.com/AI4S2S/lilio/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/AI4S2S/lilio git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-copper-terrier.sh
        container: qc.acc_shaky-sangria-hippopotamus
  QC.Doc:
    repos:
      github.com/AI4S2S/lilio find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-cinnamon-devil.sh
        container: qc.doc_grumpy-cyan-monkey
      github.com/AI4S2S/lilio git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-scarlet-hedgehog.sh
        container: qc.doc_wimpy-ecru-rattlesnake
      github.com/AI4S2S/lilio markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-tan-reindeer.sh
        container: qc.doc_ready-tangerine-pinscher
      github.com/AI4S2S/lilio restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-lilac-cheetah.sh
        container: qc.doc_fuzzy-sapphire-zonkey
  QC.Lic:
    repos:
      github.com/AI4S2S/lilio licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-mustard-jackal.sh
        container: qc.lic_leaky-jade-cuscus
  QC.Met:
    repos:
      github.com/AI4S2S/lilio cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-cinnabar-jellyfish.sh
        container: qc.met_breezy-coral-mayfly
  QC.Sec:
    repos:
      github.com/AI4S2S/lilio bandit:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-viridian-gorilla.sh
        container: qc.sec_skinny-seashell-russel
  QC.Sty:
    repos:
      github.com/AI4S2S/lilio flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-cerulean-ragdoll.sh
        container: qc.sty_squeaky-mauve-drever
      github.com/AI4S2S/lilio jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-platinum-cockroach.sh
        container: qc.sty_skimpy-ivory-lynx
  QC.Ver:
    repos:
      github.com/AI4S2S/lilio get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-orange-mole.sh
        container: qc.ver_bumpy-olivine-dalmatian
timeout: 5400
