config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/themiszamani/eosc-recommender-metrics:
      branch: QC.Doc02.X-updates
      repo: https://github.com/themiszamani/eosc-recommender-metrics/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/themiszamani/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-gold-avocet.sh
        container: qc.acc_stinky-flax-budgerigar
  QC.Doc:
    repos:
      github.com/themiszamani/eosc-recommender-metrics find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-heliotrope-hamster.sh
        container: qc.doc_flaky-zucchini-shark
      github.com/themiszamani/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-ivory-cichlid.sh
        container: qc.doc_jumpy-goldenrod-deer
      github.com/themiszamani/eosc-recommender-metrics markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-tan-dalmatian.sh
        container: qc.doc_snippy-yellow-tang
  QC.Lic:
    repos:
      github.com/themiszamani/eosc-recommender-metrics licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-cornflower-havanese.sh
        container: qc.lic_squeaky-pear-spitz
  QC.Met:
    repos:
      github.com/themiszamani/eosc-recommender-metrics cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-scarlet-mayfly.sh
        container: qc.met_crappy-cornflower-indri
  QC.Sec:
    repos:
      github.com/themiszamani/eosc-recommender-metrics bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-cardinal-hyena.sh
        container: qc.sec_chewy-chartreuse-hornet
  QC.Sty:
    repos:
      github.com/themiszamani/eosc-recommender-metrics flake8:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-yellow-koala.sh
        container: qc.sty_hazy-cardinal-scorpion
      github.com/themiszamani/eosc-recommender-metrics jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-dandelion-rhinoceros.sh
        container: qc.sty_bluesy-malachite-rhinoceros
  QC.Ver:
    repos:
      github.com/themiszamani/eosc-recommender-metrics get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-goldenrod-snake.sh
        container: qc.ver_foggy-harlequin-crocodile
timeout: 5400
