config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/themiszamani/eosc-recommender-metrics:
      branch: QC.Doc02.X-updates
      repo: https://github.com/themiszamani/eosc-recommender-metrics/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/themiszamani/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-seashell-mongoose.sh
        container: qc.acc_squirrely-khaki-tarantula
  QC.Doc:
    repos:
      github.com/themiszamani/eosc-recommender-metrics find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-peach-rottweiler.sh
        container: qc.doc_tacky-sepia-whale
      github.com/themiszamani/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-saffron-albatross.sh
        container: qc.doc_droopy-amber-camel
      github.com/themiszamani/eosc-recommender-metrics markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-razzmatazz-toucan.sh
        container: qc.doc_bumpy-russet-frog
  QC.Lic:
    repos:
      github.com/themiszamani/eosc-recommender-metrics licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-ruby-paradise.sh
        container: qc.lic_queasy-magenta-forest
  QC.Met:
    repos:
      github.com/themiszamani/eosc-recommender-metrics cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-flax-hyena.sh
        container: qc.met_homey-olive-dollar
  QC.Sec:
    repos:
      github.com/themiszamani/eosc-recommender-metrics bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-crimson-bee.sh
        container: qc.sec_gamy-xanthic-gharial
  QC.Sty:
    repos:
      github.com/themiszamani/eosc-recommender-metrics flake8:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-brown-affenpinscher.sh
        container: qc.sty_geeky-goldenrod-malamute
      github.com/themiszamani/eosc-recommender-metrics jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-chocolate-centipede.sh
        container: qc.sty_jumpy-apricot-kudu
  QC.Ver:
    repos:
      github.com/themiszamani/eosc-recommender-metrics get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-silver-dolphin.sh
        container: qc.ver_paltry-buff-ray
timeout: 5400
