config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/bsc-wdc/dislib:
      branch: master
      repo: https://github.com/bsc-wdc/dislib/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/bsc-wdc/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-aqua-bat.sh
        container: qc.acc_sloppy-orchid-frigatebird
  QC.Doc:
    repos:
      github.com/bsc-wdc/dislib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-asparagus-kudu.sh
        container: qc.doc_snippy-plum-seal
      github.com/bsc-wdc/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-vermilion-rabbit.sh
        container: qc.doc_lovely-gold-axolotl
      github.com/bsc-wdc/dislib markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-rust-blue.sh
        container: qc.doc_slaphappy-chartreuse-quetzal
      github.com/bsc-wdc/dislib restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-salmon-emu.sh
        container: qc.doc_bumpy-rose-cat
  QC.Lic:
    repos:
      github.com/bsc-wdc/dislib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-sepia-beaver.sh
        container: qc.lic_messy-lilac-flounder
  QC.Sec:
    repos:
      github.com/bsc-wdc/dislib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-lavender-cougar.sh
        container: qc.sec_slaphappy-ochre-urchin
  QC.Sty:
    repos:
      github.com/bsc-wdc/dislib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.surly-black-whippet.sh
        container: qc.sty_stinky-orchid-zorse
      github.com/bsc-wdc/dislib hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-saffron-tortoise.sh
        container: qc.sty_thirsty-purple-crab
  QC.Ver:
    repos:
      github.com/bsc-wdc/dislib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-xanthic-dolphin.sh
        container: qc.ver_shabby-scarlet-wrasse
timeout: 5400
