config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/INSPIRE-MIF/helpdesk-validator:
      branch: master
      repo: https://github.com/INSPIRE-MIF/helpdesk-validator/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/INSPIRE-MIF/helpdesk-validator git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-cardinal-cheetah.sh
        container: qc.acc_whiny-pumpkin-monster
  QC.Doc:
    repos:
      github.com/INSPIRE-MIF/helpdesk-validator find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-vermilion-guppy.sh
        container: qc.doc_leaky-beige-robin
      github.com/INSPIRE-MIF/helpdesk-validator git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-red-grasshopper.sh
        container: qc.doc_sickly-lilac-cattle
      github.com/INSPIRE-MIF/helpdesk-validator markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-russet-swan.sh
        container: qc.doc_shaggy-mustard-moose
  QC.Lic:
    repos:
      github.com/INSPIRE-MIF/helpdesk-validator licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-violet-tzu.sh
        container: qc.lic_lumpy-green-rottweiler
  QC.Ver:
    repos:
      github.com/INSPIRE-MIF/helpdesk-validator get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-zucchini-squirt.sh
        container: qc.ver_cranky-eggplant-skunk
timeout: 5400
