config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eurise-network/technical-reference:
      branch: master
      repo: https://github.com/eurise-network/technical-reference/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eurise-network/technical-reference git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-cardinal-termite.sh
        container: qc.acc_paltry-gold-akita
  QC.Doc:
    repos:
      github.com/eurise-network/technical-reference find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-magnolia-orangutan.sh
        container: qc.doc_cheeky-ivory-setter
      github.com/eurise-network/technical-reference git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cerise-ostrich.sh
        container: qc.doc_stuffy-cerulean-shrimp
      github.com/eurise-network/technical-reference markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-teal-spoonbill.sh
        container: qc.doc_scanty-ecru-moth
      github.com/eurise-network/technical-reference restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-eggplant-javanese.sh
        container: qc.doc_slaphappy-copper-dachsbracke
  QC.Lic:
    repos:
      github.com/eurise-network/technical-reference licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-turquoise-bracke.sh
        container: qc.lic_boozy-gamboge-zonkey
  QC.Sec:
    repos:
      github.com/eurise-network/technical-reference bandit:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-coral-hummingbird.sh
        container: qc.sec_homey-bronze-echidna
  QC.Sty:
    repos:
      github.com/eurise-network/technical-reference flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-cyan-penguin.sh
        container: qc.sty_surly-olivine-tapir
      github.com/eurise-network/technical-reference rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-lilac-snail.sh
        container: qc.sty_tasty-magnolia-sloth
  QC.Ver:
    repos:
      github.com/eurise-network/technical-reference get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-bistre-vulture.sh
        container: qc.ver_droopy-thistle-moose
timeout: 1800
