config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/bsc-wdc/dislib:
      branch: master
      repo: https://github.com/bsc-wdc/dislib/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/bsc-wdc/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-azure-kiwi.sh
        container: qc.acc_frumpy-sepia-ibis
  QC.Doc:
    repos:
      github.com/bsc-wdc/dislib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-salmon-chin.sh
        container: qc.doc_shaky-green-opossum
      github.com/bsc-wdc/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-ochre-chow.sh
        container: qc.doc_sleepy-sepia-zebra
      github.com/bsc-wdc/dislib markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-orange-caiman.sh
        container: qc.doc_geeky-aquamarine-sponge
      github.com/bsc-wdc/dislib restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-orchid-indri.sh
        container: qc.doc_chummy-pink-tetra
  QC.Lic:
    repos:
      github.com/bsc-wdc/dislib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-eggplant-tarantula.sh
        container: qc.lic_paltry-wheat-donkey
  QC.Sec:
    repos:
      github.com/bsc-wdc/dislib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-magnolia-fossa.sh
        container: qc.sec_scaly-ruby-toucan
  QC.Sty:
    repos:
      github.com/bsc-wdc/dislib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-peach-neanderthal.sh
        container: qc.sty_cheeky-gamboge-dugong
      github.com/bsc-wdc/dislib hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-corn-blue.sh
        container: qc.sty_whiny-goldenrod-chinook
  QC.Ver:
    repos:
      github.com/bsc-wdc/dislib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-ecru-iguana.sh
        container: qc.ver_cheeky-salmon-dragonfly
timeout: 5400
