config:
  credentials: []
  project_repos:
    earth.bsc.es/gitlab/encomienda/sdswas.products:
      branch: master
      repo: https://earth.bsc.es/gitlab/encomienda/sdswas.products/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      earth.bsc.es/gitlab/encomienda/sdswas.products git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-platinum-donkey.sh
        container: qc.acc_freaky-periwinkle-markhor
  QC.Doc:
    repos:
      earth.bsc.es/gitlab/encomienda/sdswas.products find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-viridian-hedgehog.sh
        container: qc.doc_wimpy-magenta-gerbil
      earth.bsc.es/gitlab/encomienda/sdswas.products git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-goldenrod-husky.sh
        container: qc.doc_homey-chocolate-cuscus
      earth.bsc.es/gitlab/encomienda/sdswas.products restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-amaranth-eleuth.sh
        container: qc.doc_sloppy-malachite-havanese
  QC.Lic:
    repos:
      earth.bsc.es/gitlab/encomienda/sdswas.products licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-champagne-gharial.sh
        container: qc.lic_slimy-blue-mammoth
  QC.Sec:
    repos:
      earth.bsc.es/gitlab/encomienda/sdswas.products bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-denim-frigatebird.sh
        container: qc.sec_stinky-lilac-kiwi
  QC.Sty:
    repos:
      earth.bsc.es/gitlab/encomienda/sdswas.products flake8:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-buff-shark.sh
        container: qc.sty_bluesy-lilac-koala
      earth.bsc.es/gitlab/encomienda/sdswas.products stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-emerald-lizard.sh
        container: qc.sty_silly-cinnamon-mole
  QC.Ver:
    repos:
      earth.bsc.es/gitlab/encomienda/sdswas.products get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-cerulean-peccary.sh
        container: qc.ver_dorky-seashell-civet
timeout: 1800
