config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rjdmartins/try_ibergrid2022_sqaaas:
      branch: master
      repo: https://github.com/rjdmartins/try_ibergrid2022_sqaaas/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-magnolia-koala.sh
        container: qc.acc_flaky-linen-dachshund
  QC.Doc:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-indigo-sheepdog.sh
        container: qc.doc_gloppy-ecru-ladybird
      github.com/rjdmartins/try_ibergrid2022_sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-ruby-tang.sh
        container: qc.doc_randy-linen-hummingbird
      github.com/rjdmartins/try_ibergrid2022_sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-auburn-angelfish.sh
        container: qc.doc_squirrely-viridian-bonobo
      github.com/rjdmartins/try_ibergrid2022_sqaaas restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-ochre-numbat.sh
        container: qc.doc_skimpy-indigo-wallaby
  QC.Lic:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-teal-flounder.sh
        container: qc.lic_pasty-cinnamon-capybara
  QC.Sec:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-rose-kangaroo.sh
        container: qc.sec_pokey-cyan-goose
  QC.Sty:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-red-jaguar.sh
        container: qc.sty_gummy-orange-dachsbracke
  QC.Ver:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-thistle-butterfly.sh
        container: qc.ver_whiny-fuchsia-camel
timeout: 1800
