config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/marekandreas/elpa:
      branch: master
      repo: https://github.com/marekandreas/elpa/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/marekandreas/elpa git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-chestnut-seal.sh
        container: qc.acc_fuzzy-razzmatazz-affenpinscher
  QC.Doc:
    repos:
      github.com/marekandreas/elpa find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-flax-tarantula.sh
        container: qc.doc_boozy-apricot-chihuahua
      github.com/marekandreas/elpa git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-platinum-gecko.sh
        container: qc.doc_smelly-sapphire-falcon
      github.com/marekandreas/elpa markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-red-dormouse.sh
        container: qc.doc_cloudy-violet-abyssinian
  QC.Lic:
    repos:
      github.com/marekandreas/elpa licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-grey-ant.sh
        container: qc.lic_shaggy-viridian-bongo
  QC.Sec:
    repos:
      github.com/marekandreas/elpa bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-malachite-pig.sh
        container: qc.sec_droopy-rose-wildebeest
  QC.Sty:
    repos:
      github.com/marekandreas/elpa flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-heliotrope-frog.sh
        container: qc.sty_thirsty-sapphire-hummingbird
  QC.Ver:
    repos:
      github.com/marekandreas/elpa get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-salmon-dunker.sh
        container: qc.ver_geeky-cinnabar-cheetah
timeout: 1800
