config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cvs.two:
      branch: 450-improve-SQA-rating
      repo: https://bitbucket.org/cessda/cessda.cvs.two/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-ecru-abyssinian.sh
        container: qc.acc_snazzy-platinum-rat
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-dandelion-kakapo.sh
        container: qc.doc_clammy-heliotrope-olm
      bitbucket.org/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-beige-beagle.sh
        container: qc.doc_pretty-brass-iguana
      bitbucket.org/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-aqua-mongoose.sh
        container: qc.doc_gamy-denim-dunker
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-brass-rhinoceros.sh
        container: qc.lic_lousy-khaki-terrier
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cvs.two cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-denim-tapir.sh
        container: qc.met_gamy-myrtle-earwig
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-chartreuse-chinook.sh
        container: qc.sty_queasy-tomato-okapi
      bitbucket.org/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-alizarin-bombay.sh
        container: qc.sty_grumpy-scarlet-pinscher
      bitbucket.org/cessda/cessda.cvs.two stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-burgundy-birman.sh
        container: qc.sty_homely-platinum-tiger
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-magenta-collie.sh
        container: qc.ver_sunny-gold-chimpanzee
timeout: 1800
