config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cdc.searchkit/src/master:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cdc.searchkit/src/master/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-purple-mastiff.sh
        container: qc.acc_hilly-lime-walrus
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-grey-dodo.sh
        container: qc.doc_scanty-gamboge-saola
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-orange-setter.sh
        container: qc.doc_messy-zucchini-bandicoot
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-celadon-chimpanzee.sh
        container: qc.doc_skanky-puce-salamander
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-periwinkle-numbat.sh
        container: qc.lic_droopy-blue-manatee
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-plum-bombay.sh
        container: qc.met_flimsy-pumpkin-barnacle
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-cinnamon-sloth.sh
        container: qc.sty_lanky-charcoal-dingo
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-chestnut-sloth.sh
        container: qc.sty_tacky-rose-mammoth
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-buff-spaniel.sh
        container: qc.sty_baggy-lime-ibis
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-heliotrope-flamingo.sh
        container: qc.ver_crappy-gold-panda
timeout: 5400
