config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/themiszamani/eosc-recommender-metrics:
      branch: QC.Doc02.X-updates
      repo: https://github.com/themiszamani/eosc-recommender-metrics/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/themiszamani/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-cream-otter.sh
        container: qc.acc_lousy-smalt-mouse
  QC.Doc:
    repos:
      github.com/themiszamani/eosc-recommender-metrics find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cerulean-cichlid.sh
        container: qc.doc_flabby-cerise-fish
      github.com/themiszamani/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-jade-mandrill.sh
        container: qc.doc_boozy-peach-fossa
      github.com/themiszamani/eosc-recommender-metrics markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-khaki-cichlid.sh
        container: qc.doc_tasty-champagne-birman
  QC.Lic:
    repos:
      github.com/themiszamani/eosc-recommender-metrics licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-purple-cuttlefish.sh
        container: qc.lic_shabby-coral-newt
  QC.Met:
    repos:
      github.com/themiszamani/eosc-recommender-metrics cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.ready-malachite-dodo.sh
        container: qc.met_squirrely-burgundy-uguisu
  QC.Sec:
    repos:
      github.com/themiszamani/eosc-recommender-metrics bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-wheat-deer.sh
        container: qc.sec_randy-seashell-stingray
  QC.Sty:
    repos:
      github.com/themiszamani/eosc-recommender-metrics flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cream-barnacle.sh
        container: qc.sty_beady-olivine-gecko
      github.com/themiszamani/eosc-recommender-metrics jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-yellow-angelfish.sh
        container: qc.sty_tasty-dandelion-wombat
  QC.Ver:
    repos:
      github.com/themiszamani/eosc-recommender-metrics get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-sepia-bloodhound.sh
        container: qc.ver_cranky-celadon-paradise
timeout: 5400
