config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cyfronet-fid/marketplace:
      branch: master
      repo: https://github.com/cyfronet-fid/marketplace/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cyfronet-fid/marketplace git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-beige-shark.sh
        container: qc.acc_shabby-rust-tapir
  QC.Doc:
    repos:
      github.com/cyfronet-fid/marketplace find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-violet-butterfly.sh
        container: qc.doc_queasy-maroon-kudu
      github.com/cyfronet-fid/marketplace git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-ivory-tarsier.sh
        container: qc.doc_sickly-olive-worm
      github.com/cyfronet-fid/marketplace markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-olive-argentino.sh
        container: qc.doc_hazy-ecru-seahorse
  QC.Lic:
    repos:
      github.com/cyfronet-fid/marketplace licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-burgundy-jackal.sh
        container: qc.lic_zippy-puce-leopard
  QC.Sty:
    repos:
      github.com/cyfronet-fid/marketplace jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-brass-okapi.sh
        container: qc.sty_dorky-vermilion-snail
      github.com/cyfronet-fid/marketplace rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cerulean-crane.sh
        container: qc.sty_thirsty-cinnamon-worm
  QC.Ver:
    repos:
      github.com/cyfronet-fid/marketplace get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-auburn-nightingale.sh
        container: qc.ver_scanty-orange-bobcat
timeout: 1800
