config:
  credentials: []
  project_repos:
    github.com/ARGOeu/eosc-recommender-metrics:
      branch: master
      repo: https://github.com/ARGOeu/eosc-recommender-metrics/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-aquamarine-quail.sh
        container: qc.acc_squeaky-amber-rottweiler
  QC.Doc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-cerulean-olm.sh
        container: qc.doc_snippy-green-clam
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-grey-kakapo.sh
        container: qc.doc_skanky-celadon-neanderthal
      github.com/ARGOeu/eosc-recommender-metrics markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-harlequin-havanese.sh
        container: qc.doc_snazzy-aqua-avocet
  QC.Lic:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-cinnabar-magpie.sh
        container: qc.lic_gimpy-chestnut-jackal
  QC.Sec:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-eggplant-peccary.sh
        container: qc.sec_foggy-aquamarine-elephant
  QC.Sty:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-olivine-eel.sh
        container: qc.sty_woolly-cerise-woodlouse
      github.com/ARGOeu/eosc-recommender-metrics jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-tomato-spaniel.sh
        container: qc.sty_frumpy-brass-fly
  QC.Ver:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-gamboge-flounder.sh
        container: qc.ver_sleepy-ruby-chinook
timeout: 5400
