config:
  credentials: []
  project_repos:
    earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer:
      branch: master
      repo: https://earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-orange-sparrow.sh
        container: qc.acc_skimpy-ultramarine-crane
  QC.Doc:
    repos:
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-lemon-anteater.sh
        container: qc.doc_boozy-chestnut-beetle
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-cyan-lionfish.sh
        container: qc.doc_seedy-dandelion-eagle
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-chartreuse-iguana.sh
        container: qc.doc_clammy-scarlet-dachsbracke
  QC.Lic:
    repos:
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-pear-wolfhound.sh
        container: qc.lic_thirsty-sapphire-squirrel
  QC.Sec:
    repos:
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer bandit:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-lime-fish.sh
        container: qc.sec_jumpy-amber-dollar
  QC.Sty:
    repos:
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer flake8:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-platinum-foxhound.sh
        container: qc.sty_sunny-olivine-wolfhound
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-violet-chinchilla.sh
        container: qc.sty_geeky-ultramarine-beagle
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-buff-ferret.sh
        container: qc.sty_leaky-platinum-sponge
  QC.Ver:
    repos:
      earth.bsc.es/gitlab/encomienda/interactive-forecast-viewer get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-silver-chicken.sh
        container: qc.ver_lovely-eggplant-zonkey
timeout: 1800
