config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/udocker:
      branch: devel3
      repo: https://github.com/indigo-dc/udocker/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-green-sheepdog.sh
        container: qc.acc_pokey-bistre-jellyfish
  QC.Doc:
    repos:
      github.com/indigo-dc/udocker find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-myrtle-baboon.sh
        container: qc.doc_sleepy-tangerine-wolfhound
      github.com/indigo-dc/udocker git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-ivory-gecko.sh
        container: qc.doc_nerdy-gamboge-dalmatian
      github.com/indigo-dc/udocker markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-goldenrod-abyssinian.sh
        container: qc.doc_sleazy-seashell-dragonfly
  QC.Lic:
    repos:
      github.com/indigo-dc/udocker licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-auburn-maltese.sh
        container: qc.lic_leaky-auburn-chipmunk
  QC.Met:
    repos:
      github.com/indigo-dc/udocker validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cerulean-zonkey.sh
        container: qc.met_bluesy-cream-kiwi
  QC.Sec:
    repos:
      github.com/indigo-dc/udocker bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ready-bronze-bongo.sh
        container: qc.sec_gimpy-wheat-barb
  QC.Sty:
    repos:
      github.com/indigo-dc/udocker flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-khaki-eagle.sh
        container: qc.sty_greasy-celadon-shrew
      github.com/indigo-dc/udocker jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-purple-tuatara.sh
        container: qc.sty_gamy-rose-pig
  QC.Ver:
    repos:
      github.com/indigo-dc/udocker get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-cyan-grouse.sh
        container: qc.ver_squeaky-ruby-zebu
timeout: 1800
