config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cdc.searchkit/src/master:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cdc.searchkit/src/master/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-seashell-tang.sh
        container: qc.acc_ready-dandelion-whippet
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-lemon-dollar.sh
        container: qc.doc_cheeky-russet-duck
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-wisteria-bombay.sh
        container: qc.doc_fuzzy-cream-paradise
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-asparagus-dragon.sh
        container: qc.doc_tasty-yellow-stingray
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-violet-bison.sh
        container: qc.lic_woozy-eggplant-cheetah
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-asparagus-wallaby.sh
        container: qc.met_cloudy-salmon-warthog
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-turquoise-rottweiler.sh
        container: qc.sty_randy-wisteria-dachsbracke
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-gold-discus.sh
        container: qc.sty_clammy-burgundy-buzzard
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-tan-turtle.sh
        container: qc.sty_gummy-cobalt-gorilla
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-grey-saola.sh
        container: qc.ver_silly-harlequin-coati
timeout: 5400
