config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: devel
      repo: https://github.com/grycap/im/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-black-mayfly.sh
        container: qc.acc_snoopy-cerulean-leopard
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-amber-armadillo.sh
        container: qc.doc_muzzy-crimson-bordeaux
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-cerise-shrew.sh
        container: qc.doc_wheezy-asparagus-dog
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-maroon-peccary.sh
        container: qc.doc_messy-denim-panda
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-silver-neanderthal.sh
        container: qc.doc_lanky-brown-civet
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-gold-dormouse.sh
        container: qc.lic_flabby-rose-dog
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.ready-jade-capuchin.sh
        container: qc.met_lumpy-wheat-coati
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-linen-snake.sh
        container: qc.sec_scaly-sepia-oriole
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-russet-bat.sh
        container: qc.sty_skimpy-lemon-tortoise
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-ruby-rattlesnake.sh
        container: qc.sty_foggy-orange-cougar
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-auburn-tiger.sh
        container: qc.sty_snoopy-tan-gibbon
      github.com/grycap/im rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.beady-firebrick-bombay.sh
        container: qc.sty_lousy-green-penguin
      github.com/grycap/im stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-razzmatazz-affenpinscher.sh
        container: qc.sty_snippy-charcoal-heron
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-white-antelope.sh
        container: qc.ver_foggy-cobalt-robin
timeout: 1800
